jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: GATSBY_CPU_COUNT=1 GATSBY_SKIP_ADDON_PAGES=true yarn build
      - run: yarn build-storybook
      - run: yarn chromatic --storybook-build-dir storybook-static --exit-zero-on-changes

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: \^release-[0-9]+-[0-9]+$\
