name: Push all release branches

on:
  push:
    branches:
      - master

jobs:
  push-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: ./scripts/push-all-release-branches.sh
